ID: 13793
Title: InvalidInputException: Attempting to execute an unsuccessful or closed pending query result
Description:
### What happens?

On latest nightly (`1.0.1.dev5272`), accessing Arrow data from the Python API crashes if you've viewed the result query. This does not error on latest stable (1.0.0).

### To Reproduce

```py
import duckdb
import polars as pl

df = pl.DataFrame({"a": [1, 2, 3, 4], "b": ["a", "b", "c", "d"]})
con = duckdb.connect()
sql = "SELECT * from df"
query = con.query(sql)

# Printing this query causes an error in .arrow() below
print(query)

query.arrow()
```
This raises an exception:
```
InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: INTERNAL Error: ArrowArrayStream was released by another thread/library
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

This might be related to @Tishj 's recent edits for the PyCapsule Interface, ref https://github.com/duckdb/duckdb/pull/13418

### OS:

MacOS Sonoma 14.6.1

### DuckDB Version:

1.0.1.dev5272

### DuckDB Client:

Python

### Hardware:

_No response_

### Full Name:

Kyle Barron

### Affiliation:

Development Seed

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have