ID: 15005
Title: INTERNAL Error: Attempted to access index 0 within vector of size 0
Description:
### What happens?

The below test case caused an internal error.

### To Reproduce

```sql
CREATE TABLE  t1(c1 INT );

SELECT * FROM t1 ORDER BY LIST_ZIP(FALSE);

-- INTERNAL Error:
-- Attempted to access index 0 within vector of size 0
```

### OS:

Ubuntu 22.04

### DuckDB Version:

v1.1.4-dev2283 44c3e83b29

### DuckDB Client:

CLI

### Hardware:

_No response_

### Full Name:

Suyang Zhong

### Affiliation:

NUS

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have