ID: 15447
Title: `Invalid Input Error` in self-join with Spark API
Description:
### What happens?

I get this error about aliases when doing a self-join with the Spark API

### To Reproduce

```python
import duckdb
import polars as pl

df = pl.DataFrame({'a': [1,1,2], 'b': [4,5,6]})
rel = duckdb.sql('select * from df')

import duckdb.experimental.spark as spark
sdf = spark.DataFrame(rel, None)
sdf
```
```text
┌───────┬───────┐
│   a   │   b   │
│ int64 │ int64 │
├───────┼───────┤
│     1 │     4 │
│     1 │     5 │
│     2 │     6 │
└───────┴───────┘
```
```python
sdf.join(sdf, on='a')
```
```text
---------------------------------------------------------------------------
InvalidInputException                     Traceback (most recent call last)
Cell In[8], line 1
----> 1 sdf.join(sdf, on='a')

File ~/scratch/.venv/lib/python3.12/site-packages/duckdb/experimental/spark/sql/dataframe.py:553, in DataFrame.join(self, other, on, how)
    550         return mapped_type
    552     how = map_to_recognized_jointype(how)
--> 553     result = self.relation.join(other.relation, on, how)
    554 return DataFrame(result, self.session)

InvalidInputException: Invalid Input Error: Both relations have the same alias, please change the alias of one or both relations using 'rel = rel.set_alias(<new alias>)'
```

### OS:

x86_64

### DuckDB Version:

1.1.3

### DuckDB Client:

python

### Hardware:

_No response_

### Full Name:

marco gorelli

### Affiliation:

quansight labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have