ID: 16437
Title: read_json_auto "JSON transform error in file" in line 18446744073709551615
Description:
### What happens?

A full scan on a JSON file (github events) fails with error "JSON transform error in file <file>, in line 18446744073709551615". 

Presumably the error occurs because it encounters an object containing a property name that was not encountered in the set sampled for schema detection, and that is fine.
But the problem is that the reference to "line 18446744073709551615" just cannot be right - the file only has 216470 lines. (Also, 18446744073709551615 is 2^64 - 1 which seems a little too close to be a coincidence) 

### To Reproduce

1) download https://data.gharchive.org/2025-02-25-0.json.gz and unpack
2) cd into the dir where the file is, run duckdb cli and execute query;

```
SELECT * 
FROM read_json_auto( '2025-02-25-0.json' )
```
result:

> JSON transform error in file "2025-02-25-0.json", in line 18446744073709551615: Object {"actions":"read","administration":"read","checks"... has unknown key "organization_knowledge_bases"
> Try increasing 'sample_size', reducing 'maximum_depth', specifying 'columns', 'format' or 'records' manually, setting 'ignore_errors' to true, or setting 'union_by_name' to true when reading multiple files with a different structure.


### OS:

Windows 11

### DuckDB Version:

v1.2.0 5f5512b827

### DuckDB Client:

cli

### Hardware:

x86

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have